### ISSUE TITLE
An error in barcode file

### ISSUE THREAD

**Issue by skyfall-lyc** [yiq/scBayes#1]
hi @yiq , i encountered an error "[ERROR] Unable to open barcode file: mybarcode.txt" when using docker scbayes scGenotype to analysis my data. Any reply would be greatly appreciated!!!
![Snipaste_2024-02-21_11-48-53](https://github.com/yiq/scBayes/assets/76504212/fa3afe1d-4da2-4d96-b34e-660439664015)

**Comment by yiq** [comment]
Hi @skyfall-lyc, thanks for trying scBayes out. From your post, the most likely reason I can think of is that you are not mapping your current directory into the docker container, therefore from within the container the files are not actually visible. Here is an example script I wrote for `scAssign`, but hopefully can help you with your `scGenotype` case:

```bash
#!/bin/bash

SC_ASSIGN="docker run -t -v$(pwd):/tmp -w/tmp --rm qiaoy/scbayes scAssign"

# sometimes docker output is in Windows newline style \0d\0a
# this removes the \0d to make the result compatible with linux
NEWLINE_FIX="sed -e s/\r//g"

echo "Performing pre-treatment cells assignment ..."
$SC_ASSIGN pre.assign.yml pre.genotype | $NEWLINE_FIX > pre.assign_results.tsv
echo "Done. Results written to pre.assign_results.tsv"
echo ""

echo "Performing post-treatment cells assignment ..."
$SC_ASSIGN post.assign.yml post.genotype | $NEWLINE_FIX > post.assign_results.tsv
echo "Done. Results written to post.assign_results.tsv"
echo ""
```

**Comment by skyfall-lyc** [comment]
Hi @yiq , sincerely thank you for your reply, I have solved the above error from docker according to your tips. Also, I have some new questions that I need your help with. Any reply would be greatly appreciated!!!

1. Should the _barcode-txt_ file only contain barcodes of tumor cells?
2. If the _barcode-txt_ file only contains barcodes of tumor cells, should the _variants-vcf_ from WES/WGS exclude germline mutations?
3. In the _subclones_ section of _YAML_ config file, are _fractions_ corrected by tumor purity?

**Comment by yiq** [comment]
HI @skyfall-lyc, please see below my responses:

regarding barcode-txt file, there are no hard requirement on it being only tumor cells. You can include other cell types and use scBayes as a tool to either validate that they are indeed non-tumor (being assigned to the normal clone), or potentially discover unexpected cancer cells. However, the barcode file should only include cells that are believed to be high quality cells. So you should filter out e.g. cells of low UMI count or high mitochondria contents.

regarding the variant-vcf file, yes it should exclude germline mutations. This is because scBayes only consider subclone defining mutations (i.e. those you include in the YAML file for each subclone). Germline mutations by definition won't be included in the subclone structure, so they are non-informative for the assignment process. As a rule of thumb, the variant-vcf file should really just be the union of all the individual subclone vcf files you use for your YAML file

regarding YAML config file, the fractions should not be corrected by tumor purity because the normal component should be included as one of the subclones. scBayes then take all the specified fractions, and normalize their sum to 1.

I hope that helps.

**Comment by skyfall-lyc** [comment]
Hi @yiq , your suggestions are of great help to me. Thank you very much for your help!

**Comment by yiq** [comment]
@skyfall-lyc you are welcome. I'm closing this issue for now. Feel free to open new ones if you run into more questions.
